name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 7 * * *"   # daily at 07:00 UTC

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      NEXT_TELEMETRY_DISABLED: "1"
      NODE_ENV: "production"
      CI: "true"
      PORT: "3000"
      BASE_URL: "http://localhost:3000"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers (with system deps)
        run: npx playwright install --with-deps

      - name: Build app
        run: npm run build

      - name: Setup database
        run: |
          npm run db:migrate
          npm run db:seed

      - name: Start server
        run: |
          nohup npm run start > server.log 2>&1 &
          echo $! > server.pid
          
      - name: Wait for server
        run: npx wait-on http://localhost:3000 --timeout 120000

      - name: Run e2e
        run: npm run e2e

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          if-no-files-found: ignore

      - name: Upload server logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: server-logs
          path: server.log
          if-no-files-found: ignore

      - name: Stop server
        if: always()
        run: |
          if [ -f server.pid ]; then kill $(cat server.pid) || true; fi
