name: CI

on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 12 * * *' # daily at 12:15 UTC

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm ci || npm i

      - name: Unit tests (Vitest)
        run: npm test --if-present

      - name: Install Playwright (best-effort)
        run: npx playwright install --with-deps || true

      - name: E2E (Playwright)
        run: npm run e2e --if-present || true
